# Purpose: 
#This yaml file has a standard name "dvc.yaml" and hence cant be changed.This is where
##the DAG principle manifests into dependent chaining. The order of execution which is essentially what the pipeline is maintained here.

#The flow seen below is a hard coded execution order and no conditional pipelining is available at the moment. However, multiple dvc files with 
##the desired flows can be configured and maintained with the code and a script shall be used to rename the needed flow to "dvc.yaml" so that it is employed. 

#stage--> The Name of the stage is customizable 
#deps --> Dependencies: The stage file itself and other dependent files(configs or utils) are added here.  
#params--> Parameters from the params.yaml
#outs--> Output files that are involved.

stages:
  stage_01_load_save:
    cmd: python src/stage_01_load_save.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - configs/config.yaml
    params:
      - TrainingArgument.run_name
    outs:
      - artifacts/Data/atis_intents_test.csv
      - artifacts/Data/atis_intents_train.csv
      - artifacts/Data/atis_intents.csv
 
  stage_02_prepare_data:
    cmd: python src/stage_02_prepare_dataset.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare_dataset.py
      - src/utils/all_utils.py
      - configs/config.yaml
      - artifacts/Data/atis_intents.csv
    params:
      - Dataset.test_size
      - model.base_model
      - model.use_fast
      - model.padding 
      - model.max_length 
      - model.truncation
      - TrainingArgument.run_name
    outs:
      - artifacts/Data/Dataset
      - artifacts/Data/id2label.json
      - artifacts/Data/label_num.json
      - artifacts/Data/label2id.json
      - artifacts/base_model

  stage_03_Train:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - configs/config.yaml
      - artifacts/Data/Dataset
      - artifacts/Data/label_num.json
    params:
      - TrainingArgument.Output_Dir
      - TrainingArgument.Evaluation_Strategy
      - TrainingArgument.Save_Strategy
      - TrainingArgument.Learning_Rate
      - TrainingArgument.Per_Device_Train_Batch_Size
      - TrainingArgument.Per_Device_Eval_Batch_Size
      - TrainingArgument.Save_Total_Limit
      - TrainingArgument.Num_Train_Epochs
      - TrainingArgument.Weight_Decay
      - TrainingArgument.Load_Best_Model_At_End
      - TrainingArgument.Warmup_Ratio
      - TrainingArgument.metric_name
      - TrainingArgument.Early_Stopping_patience
      - TrainingArgument.Cuda
      - TrainingArgument.report_to
      - TrainingArgument.run_name
      - TrainingArgument.WANDB_PROJECT
      - model.base_model
      - model.use_fast
      - model.padding 
      - model.max_length 
      - model.truncation
    outs:
      - artifacts/Sentence-Classif   
      - artifacts/Best_Model  
      - wandb  
  stage_04_Onnx:
    cmd: python src/stage_04_onnx.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_onnx.py
      - src/utils/all_utils.py
      - configs/config.yaml
      - artifacts/Best_Model
    params:
      - model.base_model
      - model.use_fast
      - Onnx.feature
      - Onnx.opset
      - Onnx.atol
      - TrainingArgument.run_name
    outs:
      - artifacts/Onnx_Output/model.onnx 
      - artifacts/Onnx_Output/model_compressed.onnx
      - artifacts/Onnx_Output/model_Quantized.onnx 
      - artifacts/Onnx_Output/model_compressed-opt.onnx
  stage_05_Model_Evalution:
    cmd: python src/stage_05_Model_Evaluation.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_05_Model_Evaluation.py
      - src/utils/all_utils.py
      - configs/config.yaml
      - artifacts/Onnx_Output/model.onnx 
      - artifacts/Onnx_Output/model_compressed.onnx
      - artifacts/Onnx_Output/model_Quantized.onnx 
      - artifacts/Onnx_Output/model_compressed-opt.onnx
    params:
      - TrainingArgument.run_name
      - TrainingArgument.metric_name
      - TrainingArgument.WANDB_PROJECT
     
      
       





#Deprecated Code: (Before jan10th,2022)----------------------------------------------------------------------------------
  # stage_03_dataset_split:
  #   cmd: python src/stage_03_train_test_split_dataset.py --config=configs/config.yaml --params=params.yaml
  #   deps:
  #     - src/stage_03_train_test_split_dataset.py
  #     - src/utils/all_utils.py
  #     - configs/config.yaml
  #     - artifacts/Data/Data.csv
  #   params:
  #     - Dataset.test_size
  #   outs:
  #     - artifacts/Data/Dataset
       