#PURPOSE OF THE FILE : Externalized  normal parameters and hyperparameters of the model to be used by the stages to train or predict!
#Choice of model ,padding , Learning rate , metric along with external directory etc

model:
  base_model: albert-base-v2
  use_fast: True
  padding: max_length
  max_length: 128
  truncation: True

Dataset:
  test_size: 0.1
  

  
#Hyperparams and Callback parameters
TrainingArgument:
  Output_Dir: artifacts/Sentence-Classif
  Evaluation_Strategy: epoch 
  Save_Strategy: epoch
  Learning_Rate: 0.00002 #2e-5
  Per_Device_Train_Batch_Size: 16
  Per_Device_Eval_Batch_Size: 16
  Save_Total_Limit: 5
  Num_Train_Epochs: 3
  Weight_Decay: 0.01
  Load_Best_Model_At_End: True
  Warmup_Ratio: 0.1
  metric_name: matthews_correlation
  Early_Stopping_patience: 2
  Cuda: False
  report_to: wandb  # enable logging to W&B
  run_name: albert-base-v2_Run_DVC_2
  WANDB_PROJECT: Text_Classification